upstream nodejsapp {
    server ec2-13-244-95-124.af-south-1.compute.amazonaws.com:3000;
    server ec2-13-244-95-124.af-south-1.compute.amazonaws.com:3001;
}

server {
    listen 80;
    server_name ec2-13-244-95-124.af-south-1.compute.amazonaws.com;

    location / {
        proxy_pass http://nodejsapp;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

