server {

   listen 80;
   server_name ec2-13-244-95-124.af-south-1.compute.amazonaws.com;

   location /pythonapp/ {

      proxy_pass http://ec2-13-244-95-124.af-south-1.compute.amazonaws.com:8000/;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;

   }
}
